resource_loaders:
  - name: "http_video"
    type: "http"
    parameters:
      url: "https://cdn.example.com/encrypted/video.bin"
      headers:
        Authorization: "Bearer ${API_TOKEN}"

secret_loaders:
  - name: "vault_key"
    type: "vault"
    parameters:
      server: "https://vault.example.com"
      path: "secrets/video-key"
      auth:
        type: "jwt"
        token_file: "/var/auth-token"