version: '3.2'
services:
  kbs:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
      - sh
      - -c
      - |
        # 启动主进程到后台
        restful-as --socket 0.0.0.0:8080 --config-file /etc/trustee/as-config.json &

        # 等待主进程完全启动
        while ! nc -z localhost 8080; do
          echo "Waiting for the main process to start..."
          sleep 0.1
        done

        # 执行初始化脚本
        /app/local/setup.sh --config-file /app/local/config.yaml

        # 将主进程带回前台保持运行
        fg %1
    restart: always # keep the server running
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/local/config.yaml:rw
      - ./setup.sh:/app/local/setup.sh:rw
      - ./data/sample_password:/app/local/password:rw
      - ./data/sample_policy.rego:/app/local/policy.rego:rw
    