network_config:
  proxies: [...]

resource_reader:
  - name: "model"
    type: "web_file"
    params:
      # model_type: "DeepSeek-R1-Chat"
      model_file: "DeepSeek-R1-Chat-encrypted.tar.gz"
      directory: "/home/daniel/confidential-ai/depeloyment/rpm/trustiflux/model"
      url: "http://0.0.0.0:9090"

secret_reader:
  - name: "model_password"
    type: "trustee"
    params:
      model_type: "DeepSeek-R1-Chat"
      path: "test/cai/password"
      kbs_addr: "http://0.0.0.0:8080"
      as_addr: "http://0.0.0.0:50005"
      # public_key_file: "/etc/trustee/public.pub"
      resource_file: "/home/daniel/confidential-ai/depeloyment/rpm/trustiflux/sample_password"