network_config:
  proxies: [...]

resource_writer:
  - name: "model"
    type: "web_file"
    params:
      model_type: "DeepSeek-R1-Chat"
      directory: "/tmp/confidential-ai/rpm/trustee/model"
      port: 9090
      bind_address: 0.0.0.0

secret_writer:
  - name: "model_password"
    type: "trustee"
    params:
      path: "test/cai/password"
      kbs_addr: "http://0.0.0.0:8080"
      private_key_file: "/etc/trustee/private.key"
      resource_file: "./trustee/sample_password"  # relative path is used for convenience
      policy_file: "./trustee/sample_policy.rego"  # relative path is used for convenience